name: dart_application_2
description: Student Information System Mobile App
version: 1.0.0

environment:
  sdk: ^3.9.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  uuid: ^4.4.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  table_calendar: ^3.2.0
  characters: ^1.4.1
  material_color_utilities: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
